In [3]:
#Importation

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.1


In [2]:
#Loading Dataset... After here you will have to preprocess(clean, manipulate), but you can partition the amount to give to each data

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

#Normalise dataset... But you can also Standardize the dataset
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 19s 2us/step


In [ ]:
#Building the structure of the model.

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(28, 28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])


In [1]:
#You use this to check the output of the model before it gets turned into probability

logits = model(x_train[:1]).numpy()
logits

NameError: name 'model' is not defined

In [6]:
#Now you turn it to probability

tf.nn.softmax(logits).numpy()

array([[0.0487428 , 0.08604532, 0.2343338 , 0.10033005, 0.09160408,
        0.10546018, 0.07473653, 0.09886812, 0.0791965 , 0.08068269]],
      dtype=float32)

In [7]:
#Define the loss function because you will use it when Compiling...

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], logits).numpy()

2.2494218

In [9]:
#Compile the model... Get it ready for building... Deciding on any of these parameters lies on your the purpose of the project.

model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [10]:
#Then you train your model

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.8638 - loss: 0.4731
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9548 - loss: 0.1528
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9674 - loss: 0.1068
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9743 - loss: 0.0853
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9762 - loss: 0.0773


In [12]:
#Checking how well the model performs

model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 861us/step - accuracy: 0.9751 - loss: 0.0810


[0.0810379832983017, 0.9750999808311462]

In [14]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.4408592e-09, 3.9866040e-07, 8.5841430e-06, 3.9150091e-04,
        1.3772204e-10, 4.8013959e-08, 2.1579894e-11, 9.9957496e-01,
        2.2895292e-06, 2.2177755e-05],
       [2.6938349e-07, 1.7815031e-05, 9.9992156e-01, 5.9708153e-05,
        3.3338293e-13, 6.8921764e-08, 4.2693836e-07, 1.1797806e-12,
        1.2046071e-07, 1.5226600e-13],
       [4.3753998e-06, 9.9584806e-01, 8.7477930e-04, 5.8551479e-05,
        4.4768030e-04, 7.1995069e-06, 1.9188772e-04, 1.5443667e-03,
        1.0223968e-03, 6.5293858e-07],
       [9.9991250e-01, 6.9439648e-10, 2.3433493e-05, 2.1181117e-07,
        2.4205750e-07, 1.9501268e-08, 5.4506432e-05, 2.8643069e-06,
        1.2917878e-08, 6.1711798e-06],
       [1.6627540e-05, 2.3563015e-08, 2.7916727e-05, 4.7429697e-07,
        9.3554872e-01, 1.3339914e-07, 9.0753956e-06, 5.3265656e-04,
        2.6636650e-05, 6.3837670e-02]], dtype=float32)>